# Generated by Django 5.2 on 2025-05-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_country_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_data',
        ),
    ]
