# Generated by Django 5.2 on 2025-05-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_total_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='fooditem',
            new_name='productitem',
        ),
    ]
