# Generated by Django 5.2 on 2025-05-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_fooditem_orderedfood_productitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='productitem',
            new_name='item',
        ),
    ]
