# Generated by Django 5.2 on 2025-05-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_productitem_orderedfood_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='item',
            new_name='product_item',
        ),
    ]
